# Generated by Django 3.2.8 on 2021-10-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
